/**
 * Enumeration for different states that claims can be in
 */

export default {
    PRE_ARBITRATION:"PRE_ARBITRATION",
    PRE_ARBITRATION_STAKER_IS_SETTLER:"PRE_ARBITRATION_STAKER_IS_SETTLER",
    PRE_ARBITRATION_CLAIMANT_IS_SETTLER:"PRE_ARBITRATION_CLAIMANT_IS_SETTLER",
    ARBITRATION:"ARBITRATION",
    RULED:"RULED"
}